version: "3.7"

services:
  nginx:
      image: nginx:1.17-alpine
      container_name: kanastra-nginx
      restart: unless-stopped
      ports:
        - 8888:80
      volumes:
        - ./:/var/www
        - ./docker/nginx:/etc/nginx/conf.d
      networks:
        - kanastra-network

  app:
    build:
      args:
        user: kanastra
        uid: 1000
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: kanastra-php
    container_name: kanastra-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kanastra-network

  db:
      image: mysql:8.0
      container_name: kanastra-database
      restart: unless-stopped
      environment:
         MYSQL_DATABASE: ${DB_DATABASE:-kanastra}
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
         MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      volumes:
        - storage-database:/var/lib/mysql
      ports:
        - "3388:3306"
      networks:
        - kanastra-network

volumes:
  storage-database:

networks:
  kanastra-network:
    driver: bridge
